use cosmwasm_schema::{cw_serde, QueryResponses};
use cosmwasm_std::{Binary, Uint128};

#[cw_serde]
pub struct InstantiateMsg {
    pub admin: String,
    pub initial_scale_factor: Uint128, // Scale factor for Trust Score (e.g. 1,000,000)
}

#[cw_serde]
pub enum ExecuteMsg {
    /// Submits a validated PoUW calculation block.
    SubmitBlock {
        block_height: u64,
        task_id: String,
        computation_manifest_hash: String, // SHA-256 of calculation results
        operator_signature: Binary,        // Dilithium-5 signature generated by Sentinel
    },
}

#[cw_serde]
#[derive(QueryResponses)]
pub enum QueryMsg {
    /// Retrieve details of a submitted block.
    #[returns(GetBlockResponse)]
    GetBlock { task_id: String },

    /// Retrieve consolidated Trust Score details of a Guardian.
    #[returns(GetTrustScoreResponse)]
    GetTrustScore { address: String },
}

#[cw_serde]
pub struct GetBlockResponse {
    pub submitter: String,
    pub block_height: u64,
    pub manifest_hash: String,
    pub verified: bool,
}

#[cw_serde]
pub struct GetTrustScoreResponse {
    pub continuous_score: Uint128,
    pub total_submissions: u64,
    pub last_updated_height: u64,
}
