# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import admin_pb2 as admin__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminStub(object):
    """v0.3.0 "Oculus": read-only observability surface for the operator.

    The `Admin` service is strictly an observer — it never unseals the
    vault, never mutates signer state, never emits a Dilithium-5
    signature. It is mounted on the *same* listener as the `Signer`
    service (UDS on unix, loopback TCP on Windows via $SANTUARIO_PORT)
    through `Server::builder().add_service(signer).add_service(admin)`.

    The three RPCs are the minimum substrate the War Room dashboard, the
    Telegram bot, and the Prometheus exporter all build on top of:

    GetMetrics    -> numerical signal: counters + gauges + p-quantiles.
    Powers both the exporter's /metrics endpoint and
    the War Room's "live numbers" panel.
    TailAuditLog  -> last N records from the append-only audit log.
    Powers the War Room audit panel and the bot's
    `/tail` command.
    ListPeers     -> current gossip view (addresses, last-seen, rx/tx
    counters). Powers the War Room peer panel and
    the bot's `/peers` command.

    All three are callable from *any* signer state — ready, suspended,
    or degraded. Observability MUST NOT depend on the signing path's
    health; that would make a sick node invisible to its operator.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetrics = channel.unary_unary(
                '/santuario.admin.v1.Admin/GetMetrics',
                request_serializer=admin__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=admin__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.TailAuditLog = channel.unary_unary(
                '/santuario.admin.v1.Admin/TailAuditLog',
                request_serializer=admin__pb2.TailAuditLogRequest.SerializeToString,
                response_deserializer=admin__pb2.TailAuditLogResponse.FromString,
                _registered_method=True)
        self.ListPeers = channel.unary_unary(
                '/santuario.admin.v1.Admin/ListPeers',
                request_serializer=admin__pb2.ListPeersRequest.SerializeToString,
                response_deserializer=admin__pb2.ListPeersResponse.FromString,
                _registered_method=True)


class AdminServicer(object):
    """v0.3.0 "Oculus": read-only observability surface for the operator.

    The `Admin` service is strictly an observer — it never unseals the
    vault, never mutates signer state, never emits a Dilithium-5
    signature. It is mounted on the *same* listener as the `Signer`
    service (UDS on unix, loopback TCP on Windows via $SANTUARIO_PORT)
    through `Server::builder().add_service(signer).add_service(admin)`.

    The three RPCs are the minimum substrate the War Room dashboard, the
    Telegram bot, and the Prometheus exporter all build on top of:

    GetMetrics    -> numerical signal: counters + gauges + p-quantiles.
    Powers both the exporter's /metrics endpoint and
    the War Room's "live numbers" panel.
    TailAuditLog  -> last N records from the append-only audit log.
    Powers the War Room audit panel and the bot's
    `/tail` command.
    ListPeers     -> current gossip view (addresses, last-seen, rx/tx
    counters). Powers the War Room peer panel and
    the bot's `/peers` command.

    All three are callable from *any* signer state — ready, suspended,
    or degraded. Observability MUST NOT depend on the signing path's
    health; that would make a sick node invisible to its operator.

    """

    def GetMetrics(self, request, context):
        """Pull every exposed metric in a single round-trip. Stable shape:
        adding a metric bumps `schema_version` and clients MUST tolerate
        unknown keys.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TailAuditLog(self, request, context):
        """Fetch the most recent `limit` records from the audit log. The
        server caps `limit` at 1000 regardless of what the client asks
        for. Returns in on-disk order (oldest-first within the window).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Snapshot the gossip peer table. The server does NOT poke peers
        during this call; it only reports what the Sentinel already
        knows.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=admin__pb2.GetMetricsRequest.FromString,
                    response_serializer=admin__pb2.GetMetricsResponse.SerializeToString,
            ),
            'TailAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.TailAuditLog,
                    request_deserializer=admin__pb2.TailAuditLogRequest.FromString,
                    response_serializer=admin__pb2.TailAuditLogResponse.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=admin__pb2.ListPeersRequest.FromString,
                    response_serializer=admin__pb2.ListPeersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'santuario.admin.v1.Admin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('santuario.admin.v1.Admin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Admin(object):
    """v0.3.0 "Oculus": read-only observability surface for the operator.

    The `Admin` service is strictly an observer — it never unseals the
    vault, never mutates signer state, never emits a Dilithium-5
    signature. It is mounted on the *same* listener as the `Signer`
    service (UDS on unix, loopback TCP on Windows via $SANTUARIO_PORT)
    through `Server::builder().add_service(signer).add_service(admin)`.

    The three RPCs are the minimum substrate the War Room dashboard, the
    Telegram bot, and the Prometheus exporter all build on top of:

    GetMetrics    -> numerical signal: counters + gauges + p-quantiles.
    Powers both the exporter's /metrics endpoint and
    the War Room's "live numbers" panel.
    TailAuditLog  -> last N records from the append-only audit log.
    Powers the War Room audit panel and the bot's
    `/tail` command.
    ListPeers     -> current gossip view (addresses, last-seen, rx/tx
    counters). Powers the War Room peer panel and
    the bot's `/peers` command.

    All three are callable from *any* signer state — ready, suspended,
    or degraded. Observability MUST NOT depend on the signing path's
    health; that would make a sick node invisible to its operator.

    """

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.admin.v1.Admin/GetMetrics',
            admin__pb2.GetMetricsRequest.SerializeToString,
            admin__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TailAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.admin.v1.Admin/TailAuditLog',
            admin__pb2.TailAuditLogRequest.SerializeToString,
            admin__pb2.TailAuditLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.admin.v1.Admin/ListPeers',
            admin__pb2.ListPeersRequest.SerializeToString,
            admin__pb2.ListPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
