# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import signer_pb2 as signer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in signer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignerStub(object):
    """v0.2.0 "Custos": the signer is no longer a bare Dilithium-5 oracle.
    Every `Sign` carries an AGP-v1 block; the signer runs the critic's
    three checks (reflexive, symbolic, axiomatic) and verifies the
    producer PID's seccomp attestation before emitting a signature. A
    suspended signer (α/β/γ threshold) rejects every Sign regardless.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sign = channel.unary_unary(
                '/santuario.signer.v1.Signer/Sign',
                request_serializer=signer__pb2.SignRequest.SerializeToString,
                response_deserializer=signer__pb2.SignResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/santuario.signer.v1.Signer/Verify',
                request_serializer=signer__pb2.VerifyRequest.SerializeToString,
                response_deserializer=signer__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.GetPublicKey = channel.unary_unary(
                '/santuario.signer.v1.Signer/GetPublicKey',
                request_serializer=signer__pb2.GetPublicKeyRequest.SerializeToString,
                response_deserializer=signer__pb2.GetPublicKeyResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/santuario.signer.v1.Signer/GetStatus',
                request_serializer=signer__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=signer__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.TriggerAudit = channel.unary_unary(
                '/santuario.signer.v1.Signer/TriggerAudit',
                request_serializer=signer__pb2.TriggerAuditRequest.SerializeToString,
                response_deserializer=signer__pb2.TriggerAuditResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/santuario.signer.v1.Signer/Resume',
                request_serializer=signer__pb2.ResumeRequest.SerializeToString,
                response_deserializer=signer__pb2.ResumeResponse.FromString,
                _registered_method=True)


class SignerServicer(object):
    """v0.2.0 "Custos": the signer is no longer a bare Dilithium-5 oracle.
    Every `Sign` carries an AGP-v1 block; the signer runs the critic's
    three checks (reflexive, symbolic, axiomatic) and verifies the
    producer PID's seccomp attestation before emitting a signature. A
    suspended signer (α/β/γ threshold) rejects every Sign regardless.

    """

    def Sign(self, request, context):
        """Sign an AGP-v1 block. The block is the canonical JSON bytes of
        the full envelope (header, payload, reproducibility, results,
        security). On success the server returns a Dilithium-5 detached
        signature over SHA-256(payload || reproducibility || results).

        Errors (Status codes):
        FAILED_PRECONDITION   -> signer is suspended (see GetStatus)
        PERMISSION_DENIED     -> PID attestation failed
        INVALID_ARGUMENT      -> block parse / schema violation
        ABORTED               -> reflexive / symbolic / axiomatic
        violation (see Violation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Verify a detached Dilithium-5 signature against a payload hash.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKey(self, request, context):
        """Fetch the public key used by this signer. Guardians publish this
        on the gossip network as part of their identity block.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Report the current operational status of the signer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerAudit(self, request, context):
        """Manually trigger the α integrity sweep now. Used by
        `santuarioctl audit --now` for tests / drills.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Operator-signed resume: present a Dilithium-5 signature over the
        outstanding challenge to clear a suspension.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=signer__pb2.SignRequest.FromString,
                    response_serializer=signer__pb2.SignResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=signer__pb2.VerifyRequest.FromString,
                    response_serializer=signer__pb2.VerifyResponse.SerializeToString,
            ),
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=signer__pb2.GetPublicKeyRequest.FromString,
                    response_serializer=signer__pb2.GetPublicKeyResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=signer__pb2.GetStatusRequest.FromString,
                    response_serializer=signer__pb2.GetStatusResponse.SerializeToString,
            ),
            'TriggerAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerAudit,
                    request_deserializer=signer__pb2.TriggerAuditRequest.FromString,
                    response_serializer=signer__pb2.TriggerAuditResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=signer__pb2.ResumeRequest.FromString,
                    response_serializer=signer__pb2.ResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'santuario.signer.v1.Signer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('santuario.signer.v1.Signer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Signer(object):
    """v0.2.0 "Custos": the signer is no longer a bare Dilithium-5 oracle.
    Every `Sign` carries an AGP-v1 block; the signer runs the critic's
    three checks (reflexive, symbolic, axiomatic) and verifies the
    producer PID's seccomp attestation before emitting a signature. A
    suspended signer (α/β/γ threshold) rejects every Sign regardless.

    """

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.signer.v1.Signer/Sign',
            signer__pb2.SignRequest.SerializeToString,
            signer__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.signer.v1.Signer/Verify',
            signer__pb2.VerifyRequest.SerializeToString,
            signer__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.signer.v1.Signer/GetPublicKey',
            signer__pb2.GetPublicKeyRequest.SerializeToString,
            signer__pb2.GetPublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.signer.v1.Signer/GetStatus',
            signer__pb2.GetStatusRequest.SerializeToString,
            signer__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.signer.v1.Signer/TriggerAudit',
            signer__pb2.TriggerAuditRequest.SerializeToString,
            signer__pb2.TriggerAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santuario.signer.v1.Signer/Resume',
            signer__pb2.ResumeRequest.SerializeToString,
            signer__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
