# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'signer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csigner.proto\x12\x13santuario.signer.v1\"#\n\x0bSignRequest\x12\x14\n\x0cpayload_hash\x18\x01 \x01(\x0c\"!\n\x0cSignResponse\x12\x11\n\tsignature\x18\x01 \x01(\x0c\"L\n\rVerifyRequest\x12\x14\n\x0cpayload_hash\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x12\n\npublic_key\x18\x03 \x01(\x0c\"\x1f\n\x0eVerifyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\"\x15\n\x13GetPublicKeyRequest\"*\n\x14GetPublicKeyResponse\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x32\x8d\x02\n\x06Signer\x12K\n\x04Sign\x12 .santuario.signer.v1.SignRequest\x1a!.santuario.signer.v1.SignResponse\x12Q\n\x06Verify\x12\".santuario.signer.v1.VerifyRequest\x1a#.santuario.signer.v1.VerifyResponse\x12\x63\n\x0cGetPublicKey\x12(.santuario.signer.v1.GetPublicKeyRequest\x1a).santuario.signer.v1.GetPublicKeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNREQUEST']._serialized_start=37
  _globals['_SIGNREQUEST']._serialized_end=72
  _globals['_SIGNRESPONSE']._serialized_start=74
  _globals['_SIGNRESPONSE']._serialized_end=107
  _globals['_VERIFYREQUEST']._serialized_start=109
  _globals['_VERIFYREQUEST']._serialized_end=185
  _globals['_VERIFYRESPONSE']._serialized_start=187
  _globals['_VERIFYRESPONSE']._serialized_end=218
  _globals['_GETPUBLICKEYREQUEST']._serialized_start=220
  _globals['_GETPUBLICKEYREQUEST']._serialized_end=241
  _globals['_GETPUBLICKEYRESPONSE']._serialized_start=243
  _globals['_GETPUBLICKEYRESPONSE']._serialized_end=285
  _globals['_SIGNER']._serialized_start=288
  _globals['_SIGNER']._serialized_end=557
# @@protoc_insertion_point(module_scope)
