//! BIP-39 seed phrase → Sigillum key derivation (Phase D operator tooling).
//!
//! ## Derivation chain
//!
//! ```text
//! BIP-39 24 words  (English wordlist, operator paper-backup mandatory)
//!        |  PBKDF2-HMAC-SHA512(salt="mnemonic", iter=2048) — via bip39 crate
//!        v
//! 512-bit BIP-39 seed
//!        |  take first 32 bytes as IKM
//!        v
//! HKDF-SHA256 ─────────── info = "aeterna-sigillum-master-log-key-v1"
//!                    └──► 32-byte MasterLogKey (feed into santuario-cipher)
//!             └────────── info = "aeterna-sigillum-ratchet-identity-v1"
//!                    └──► 32-byte X25519 secret (feed into SignerIdentityKey)
//! ```
//!
//! Neither the BIP-39 seed nor the IKM are persisted. The operator
//! re-derives on each boot from the `seed.bip39` file.
//!
//! ## Security notes
//!
//! * The 24-word phrase should be generated by a CSPRNG (BIP-39
//!   entropy = 256 bits). Do NOT generate phrases manually — the
//!   wordspace must be uniformly sampled.
//! * PBKDF2 with 2048 iterations is the BIP-39 standard. For 2025
//!   threat models, this is deliberately minimal — hardware key support
//!   (YubiKey PIV) is the v1.0 upgrade path per the sprint plan.
//! * The passphrase is fixed to "" (no passphrase). Passphrase support
//!   would require an additional interactive prompt in santuarioctl,
//!   and the v0.4 sprint explicitly decided against it.

use bip39::Mnemonic;
use hkdf::Hkdf;
use sha2::Sha256;
use zeroize::Zeroize;

use crate::error::{Error, Result};

const LOG_KEY_INFO: &[u8] = b"aeterna-sigillum-master-log-key-v1";
const RATCHET_ID_INFO: &[u8] = b"aeterna-sigillum-ratchet-identity-v1";

/// Keys derived from a BIP-39 mnemonic. Both fields are zeroized on drop.
pub struct SigillumKeys {
    /// 32-byte master key for the audit log segments.
    /// Pass to `santuario_cipher::MasterLogKey::from_bytes`.
    pub master_log_key: [u8; 32],
    /// 32-byte X25519 secret for the signer's long-term identity.
    /// Pass to `santuario_ratchet::SignerIdentityKey::from_bytes`.
    pub ratchet_identity: [u8; 32],
}

impl Drop for SigillumKeys {
    fn drop(&mut self) {
        self.master_log_key.zeroize();
        self.ratchet_identity.zeroize();
    }
}

/// Parse and validate a BIP-39 24-word English mnemonic from a phrase string.
///
/// Accepts words separated by any whitespace (spaces, newlines). Leading/
/// trailing whitespace is stripped. The phrase must contain exactly 24 valid
/// BIP-39 English words with a correct checksum.
pub fn parse_mnemonic(phrase: &str) -> Result<Mnemonic> {
    // Normalise whitespace: collapse runs to a single space before parsing,
    // so files with trailing newlines or double-spaced words are accepted.
    let normalised: String = phrase.split_whitespace().collect::<Vec<_>>().join(" ");
    Mnemonic::parse_normalized(&normalised).map_err(|e| Error::Bip39(e.to_string()))
}

/// Derive Sigillum operational keys from a validated BIP-39 mnemonic.
///
/// The BIP-39 PBKDF2 uses no passphrase (the standard empty-string
/// convention). The 512-bit BIP-39 seed is then fed into HKDF-SHA256
/// with separate `info` labels to produce two independent 32-byte keys.
pub fn derive_from_mnemonic(mnemonic: &Mnemonic) -> Result<SigillumKeys> {
    // Standard BIP-39 PBKDF2-HMAC-SHA512, 2048 iterations.
    // `to_seed("")` handles this internally; result is [u8; 64].
    let seed = mnemonic.to_seed("");
    let ikm = &seed[..32];

    let hk = Hkdf::<Sha256>::new(None, ikm);

    let mut master_log_key = [0u8; 32];
    hk.expand(LOG_KEY_INFO, &mut master_log_key)
        .map_err(|_| Error::Kdf("hkdf master-log-key expand failed"))?;

    let mut ratchet_identity = [0u8; 32];
    hk.expand(RATCHET_ID_INFO, &mut ratchet_identity)
        .map_err(|_| Error::Kdf("hkdf ratchet-identity expand failed"))?;

    // seed lives on the stack and goes out of scope here. The critical
    // material (master_log_key, ratchet_identity) is in SigillumKeys
    // which zeroizes on drop.
    Ok(SigillumKeys {
        master_log_key,
        ratchet_identity,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_PHRASE_24: &str =
        "abandon abandon abandon abandon abandon abandon abandon abandon \
         abandon abandon abandon abandon abandon abandon abandon abandon \
         abandon abandon abandon abandon abandon abandon abandon art";

    #[test]
    fn parse_known_mnemonic() {
        let m = parse_mnemonic(TEST_PHRASE_24).unwrap();
        assert_eq!(m.word_count(), 24);
    }

    #[test]
    fn parse_rejects_invalid_word() {
        let bad = "notaword ".repeat(24);
        assert!(parse_mnemonic(&bad).is_err());
    }

    #[test]
    fn parse_rejects_wrong_checksum() {
        // All "abandon"s except the last — that produces a bad checksum.
        let bad = "abandon ".repeat(24);
        assert!(parse_mnemonic(&bad).is_err());
    }

    #[test]
    fn derive_produces_32_byte_keys() {
        let m = parse_mnemonic(TEST_PHRASE_24).unwrap();
        let keys = derive_from_mnemonic(&m).unwrap();
        assert_eq!(keys.master_log_key.len(), 32);
        assert_eq!(keys.ratchet_identity.len(), 32);
    }

    #[test]
    fn derive_is_deterministic() {
        let m = parse_mnemonic(TEST_PHRASE_24).unwrap();
        let k1 = derive_from_mnemonic(&m).unwrap();
        let k2 = derive_from_mnemonic(&m).unwrap();
        assert_eq!(k1.master_log_key, k2.master_log_key);
        assert_eq!(k1.ratchet_identity, k2.ratchet_identity);
    }

    #[test]
    fn log_key_and_ratchet_identity_are_distinct() {
        let m = parse_mnemonic(TEST_PHRASE_24).unwrap();
        let keys = derive_from_mnemonic(&m).unwrap();
        assert_ne!(keys.master_log_key, keys.ratchet_identity);
    }

    #[test]
    fn whitespace_normalisation() {
        // File with trailing newline + double-space between words must parse.
        let phrase_with_extra_ws =
            "\n  abandon  abandon abandon abandon abandon abandon abandon abandon \
             abandon abandon abandon abandon abandon abandon abandon abandon \
             abandon abandon abandon abandon abandon abandon abandon art  \n";
        let m = parse_mnemonic(phrase_with_extra_ws).unwrap();
        assert_eq!(m.word_count(), 24);
    }
}
